config/routes.rb
Shop::Application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  scope '(:locale)' do
    resources :users
    resources :orders
    resources :line_items do
      post 'decrement', on: :member
      post 'increment', on: :member
    end
    resources :carts
    resources :products do
      get :who_bought, on: :member
    end
    root to: 'store#index', as: 'store'
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :image_url, :price, :title

  has_many :line_items
  has_many :orders, through: :line_items

  #here we prevent any deleting action for a product whitch can be in a cart
  before_destroy :ensure_not_referenced_by_any_line_item

  #ensure that there are no line items referencing this product
  def ensure_not_referenced_by_any_line_item
    if line_items.count.zero?
      return true
    else
      error[:base] << "Line Items present"
      return false
    end
  end
  
  #settind a default scope to classify a request to db order by title
  default_scope :order => 'title'

  #validates that the following fields have some date in them
  validates :title, :description, :image_url, :presence => true

  #validates that the price is a positive number
  validates :price, :numericality => {:greater_than_or_equal_to => 0.01}

  #validates that the title is unique
  validates :title, :uniqueness => true

  #validates format for product's image
  validates :image_url, :format => {
  	:with => %r{\.(gif|jpg|png)$}i,
  	:message => 'must be a url for GIF, PNG, JPG image.'
  }

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_filter :authorize, only: [:show]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  def who_bought
    @product = Product.find(params[:id])
    respond_to do |format|
      format.atom #who_bought.atom.builder

    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows => 6 %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="twelve columns">
<h3>Listing products</h3>
<h5 class="subheader">Here is the place to manage all your products</h5>
<button><%= link_to 'New Product', new_product_path %></button>
<hr>
<table border="1">
  <tr>
    <th>Cover</th>
    <th>Title</th>
    <th>Description</th>
    <th>Price</th>
    <th colspan="3">Actions</th>
  </tr>
  <% @products.each do |product| %>
    <tr>
        <td><%= image_tag product.image_url %></td>
        <td><%= product.title %></td>
        <td><%=raw truncate(product.description, :length => 200) %></td>
        <td><%= number_to_currency(product.price) %></td>
        <td>
          <%= link_to 'Show', product %>
        </td>
        <td>
          <%= link_to 'Edit', edit_product_path(product) %>
        </td>
        <td>
          <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
    </tr>
  <% end %>
</table>
</div>

app/views/products/new.html.erb
<div class="row">
	<div class="twelve columns">
		<h1>New product</h1>

		<%= render 'form' %>

		<%= link_to 'Back', products_path %>
	</div>
</div>

app/views/products/show.html.erb
<div class="row">
  	<div class="twelve columns">
		<p id="notice"><%= notice %></p>
		<article>
			<h3><a href="#"><%= @product.title %></a></h3>
			<hr>
			<div class="row">
				<div class="six columns">
					<%= image_tag @product.image_url, :width => '200' %>
				</div>
				<div class="six columns">
					<h6><b>Description :</b></h6>
					<p><%=sanitize @product.description %></p>
					<p>
						<b><%= t('.price_show') %> : <%= number_to_currency(@product.price) %></b>
						<span><%= button_to t('.buy_show'), line_items_path(:product_id => @product) %></span>
					</p>
				</div>
			</div>
		</article>
		<br>
		<% if session[:user_id] %>
			<%= link_to t('.edit_show'), edit_product_path(@product) %> |
			<%= link_to t('.back_show'), products_path %>
		<% else %>
			<%= link_to t('.back_show'), store_path %>
		<% end %>
	</div>
</div>