config/routes.rb
Shop::Application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  scope '(:locale)' do
    resources :users
    resources :orders
    resources :line_items do
      post 'decrement', on: :member
      post 'increment', on: :member
    end
    resources :carts
    resources :products do
      get :who_bought, on: :member
    end
    root to: 'store#index', as: 'store'
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Monkey Dojo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>
    <!-- Navigation -->

      <div class="row">
        <div class="twelve columns">

          <ul class="top-bar">

            <ul>
              <li class="name"><h1><a href="#">Monkey Dojo</a></h1></li>
              <li class="toggle-topbar"><a href="#"></a></li>
            </ul>
          
            <section>
              <ul class="left">
                <li><%= link_to t('.home'), '/' %></li>
                <li><a href="#"><%=t('.about')%></a></li>
                <li><a href="#"><%=t('.contact')%></a></li>
                <li>
                  <%= form_tag store_path, class: 'locale' do %>
                    <%= select_tag 'set_locale', options_for_select(LANGUAGES, I18n.locale.to_s), onchange: 'this.form.submit()' %>
                    <%= submit_tag 'submit' %>
                    <%= javascript_tag "$('.locale input').hide()" %>
                  <% end %>
                </li>
              </ul>
              <% if session[:user_id] %>
              <ul class="right">
                <li class="has-dropdown">
                  <a href="#"><%= t('.tool') %></a>

                  <ul class="dropdown">
                    <li><%= link_to t('.orders'), orders_path %></li>
                    <li><%= link_to t('.products'), products_path %></li>
                    <li><%= link_to t('.users'), users_path %></li>
                    <li><%= link_to t('.logout'), logout_path, method: :delete %></li>
                  </ul>
                </li>
              </ul>
              <% end %>
            </section>
          </ul>
      </div>
    </div>
    <!-- End Navigation -->
<div class="row">
  <div class="twelve columns">
    <p style="color:green" id="notice"><big><%= notice %></big></p>
      <div class="row">
        <%= yield %>
      </div>
  </div>
</div>


<!-- Footer -->

    <footer class="row">
      <div class="twelve columns"><hr />
        <div class="row">

          <div class="six columns">
            <p>&copy; <a href="http://bemonkey.net">Be Monkey</a>.</p>
          </div>

          <div class="six columns">
            <ul class="link-list right">
              <li><%= link_to t('.home'), '/' %></li>
              <li><a href="#"><%=t('.about')%></a></li>
              <li><a href="#"><%=t('.contact')%></a></li>
              </ul>
          </div>

        </div>
      </div>
    </footer>

  <!-- End Footer -->

</body>
</html>